### ISSUE TITLE
SVG issues

### ISSUE THREAD

**Issue by acabal** [itsayellow/p-g-wodehouse_love-among-the-chickens#3]
- titlepage.svg height should match the contents plus some padding. See the art manual. You can copy and paste the viewbox from another 3-line titlepage
- Both in cover.svg and titlepage.svg, "P.G." needs a space between the initials. Remember to update the `<title>` tags too!
- After these are updated, remember to run `build-images` again.

**Comment by acabal** [comment]
Also, the spacing between the title and author in titlepage.svg is too large. See the art manual for appropriate spacing. You can copy and paste all of those values from a different title with the same appearance.

**Comment by itsayellow** [comment]
(fixed and ran build-images again)
