### ISSUE TITLE
Run typogrify and semanticate again

### ISSUE THREAD

**Issue by acabal** [itsayellow/p-g-wodehouse_love-among-the-chickens#5]
They both make additional changes. Note that for `semanticate` we don't want to accept all the changes it makes... I think only changes to chapter-8 and the ToC should be accepted for `semanticate`.

**Comment by itsayellow** [comment]
One of the changes that typogrify makes seems to be in conflict with the Standard Ebooks Typography Manual.

It wants to add a space between the ellipses and a question mark, which is specifically disallowed in the Typography Manual.

On Chapter 3, it wants to change:

> “Excuse me,” I said, “I think …?”

to:
> “Excuse me,” I said, “I think … ?”

I think I went back and fixed this manually after running typogrify before, after consulting the Typography Manual.

**Comment by itsayellow** [comment]
Another thing typogrify wants to do that I'm not sure about.  It wants to add a space between an em-dash and an ellipses.

The Typography Manual says to "Place a hair space (U+200A) glyph before all ellipses that are not directly preceded by punctuation"  Does an em-dash qualify as punctuation (and therefore not get a hair space?)

On Chapter 7, it wants to change:
> “I must apol⁠—…” I began, and ended the sentence with gulps.


to (difficult to see the hairspace here):
> “I must apol⁠— …” I began, and ended the sentence with gulps.

**Comment by acabal** [comment]
Very good catch!

Re. question marks, the manual explicitly disallows them between ellipses and *quotation* marks (not question marks) but the example directly below that statement doesn't have a hair space before the question mark, like it should. I think this is just a typo in the example, because the script explicitly includes question marks in that match when putting spaces in.  So, let's do what `typogrify` does, and I'll fix the typo in the manual.

Re. em dashes, I would say that yes, em dashes are punctuation, however I think in this case it looks better with a hair space in there. This is actually an extremely rare case, there is only one single other "em dash--ellipses" construct in our entire corpus. (*Chickens* will be the 2nd.) So again, stick with what `typogrify` does, and I'll update the manual for this case.

**Comment by itsayellow** [comment]
Oh wow, the Typography Manual does say "quotation" marks, my brain just substituted the other q-word when I looked at the example.  Ha!

Cool.  I'll just let typogrify do its thing for these then.
