### ISSUE TITLE
Put a space between all instances of HathiTrust (e.g. Hathi Trust)

### ISSUE THREAD

**Issue by acabal** [itsayellow/p-g-wodehouse_love-among-the-chickens#8]

**Comment by itsayellow** [comment]
What about their style guide saying specifically to call them "HathiTrust"?
https://www.hathitrust.org/contact

> Style Guide
> USE "HathiTrust"
> NOT "Hathi"
> NOT "Hathi Trust"

**Comment by acabal** [comment]
I wasn't aware of that; we'll have to change it project-wide, but for 
now just stick to Hathi Trust and we can change everything all at once 
later.

**Comment by itsayellow** [comment]
will do.
